{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "16239466"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-metadata-1.12.1.jar",
          "url": "ui-tooling-1.12.1.jar",
          "size": 5038,
          "sha512": "35fe22848dd5dfaaa5c0a91f3b8f24e4c1178b31f3d5ca7c5bca070db9ecc382638739dece18ca1056cb2f750113c1f0dd0c7350de91b086f43047215e817be2",
          "sha256": "cf1c064de5ddf5d216616bcfdc07b8394057910ee189d7a4d792a5f286933b57",
          "sha1": "e2fbead4c1a07a0f96c05daaa12587905e178ece",
          "md5": "957bf03a929620427679d9e0da8001a6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-kotlin-1.12.1-sources.jar",
          "url": "ui-tooling-1.12.1-sources.jar",
          "size": 9303,
          "sha512": "1b7cb6c27a42c215aea0ad85f3c6b54dbd06e8756e1168e4c42c6dcf6f07afa56cf317253642b3c1708ad20c12cafd6c6ba33f8a3a7c2f50d539887e9043c41f",
          "sha256": "c3a807eb0f92d453fb2822f0e98b80b95166b7bb9c750fa381e1d4dcf0534928",
          "sha1": "a2a29799fb748b72f2148d74a5e047b40cc8289d",
          "md5": "92d4e91d929922213d9c382febc06d7d"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-1.12.1-multiplatform-sources.jar",
          "url": "ui-tooling-1.12.1-multiplatform-sources.jar",
          "size": 70101,
          "sha512": "608c5e56cc6a725bb00c3fbe5732f3554dc24c710777bbb078fa623e008a60c32f77333b036925bf7b692eefda7c2d2c442cbb8a2005b3f9cad6ef8228e693a8",
          "sha256": "91245bae9f9d9bb82cb060708b788edbf76b25d405356265729dc33adbadf303",
          "sha1": "e338598dd6efa2fdfa3b968cc1781fe6bba9d9b8",
          "md5": "4a57587853379b29a2bd1353029d4594"
        },
        {
          "name": "ui-tooling-1.12.1-samples-sources.jar",
          "url": "ui-tooling-1.12.1-samples-sources.jar",
          "size": 36616,
          "sha512": "d028ec4d8da2a17c6d5643229ace9c031a83a001a8be623f758cd3a13b55a548f336d899d8b8e0cb3c63986ce36c4f85f2a53109310aec8477f798c107aa594c",
          "sha256": "f8f99f503f7a662a22078a2eda1e7ed2eceacfcd1191bf22f06ee445da284e9c",
          "sha1": "25a713892c708d8be104e0c7f716b38155bae9ef",
          "md5": "fc76b685ef600693b50d9b405ca12455"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-tooling-1.12.1-versionMetadata.json",
          "size": 1491,
          "sha512": "ab2c010ebb55173cc0b1e119473243a54c44dc8f1a949ff859b6df8ce9ce72b250ea8406c52985c07cab7111a04e0584cda4d6e15a54b2d4825256871d25be74",
          "sha256": "b3533f1504376bf3bd798527b9422f8d20dc863719e80db8b55c753794e88ebd",
          "sha1": "5c0abe4490faca4f5491de7dc29295cd0df62a66",
          "md5": "d0a836f23f04a5e714ace4f29be997c8"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-tooling-android/1.12.1/ui-tooling-android-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-android",
        "version": "1.12.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-tooling-android/1.12.1/ui-tooling-android-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-android",
        "version": "1.12.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-tooling-android/1.12.1/ui-tooling-android-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-android",
        "version": "1.12.1"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-jvmstubs/1.12.1/ui-tooling-jvmstubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-jvmstubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-jvmstubs/1.12.1/ui-tooling-jvmstubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-jvmstubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-jvmstubs/1.12.1/ui-tooling-jvmstubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-tooling-jvmstubs",
        "version": "1.12.1"
      }
    }
  ]
}