{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.11.1.aar",
          "url": "media3-exoplayer-1.11.1.aar",
          "size": 1703377,
          "sha512": "aaabadbcc434e6eb26c6ec34e8fb306b5311651804e584f3bdc5708fd617e1be4c66298ca689d31bfbecab920c903c56cdb7d17a196a77f25b9b68f0d350fc14",
          "sha256": "588592baec110837c33ce0c82bb76464203e6b0621177bbe5d88779001a6f1ed",
          "sha1": "dbd6edc8c5eb12e6ef2ff119d9580b0b5eca221f",
          "md5": "b075183a33a3dc83af8fb342e8b28d82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.11.1.aar",
          "url": "media3-exoplayer-1.11.1.aar",
          "size": 1703377,
          "sha512": "aaabadbcc434e6eb26c6ec34e8fb306b5311651804e584f3bdc5708fd617e1be4c66298ca689d31bfbecab920c903c56cdb7d17a196a77f25b9b68f0d350fc14",
          "sha256": "588592baec110837c33ce0c82bb76464203e6b0621177bbe5d88779001a6f1ed",
          "sha1": "dbd6edc8c5eb12e6ef2ff119d9580b0b5eca221f",
          "md5": "b075183a33a3dc83af8fb342e8b28d82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.11.1-sources.jar",
          "url": "media3-exoplayer-1.11.1-sources.jar",
          "size": 1230148,
          "sha512": "334551fce42a8d0dd5966501f5f3ab83b64217de689aa1a8171606b19504638382ea33c33b3057d59e64a9803e03d950c35eb0782f4dc5f4b297097188032669",
          "sha256": "a13b3e52cf278f147020d9b98f29ebd5a19e1dc0798f02595c6849291eb33233",
          "sha1": "785e2f15cfbc842033e64f4883c44efdd86319cf",
          "md5": "b4b87506213cfaccb1aeb6609864c395"
        }
      ]
    }
  ]
}
