{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-extended/1.7.8/material-icons-extended-1.7.8.module",
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.7.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-desktop-1.7.8.jar",
          "url": "material-icons-extended-desktop-1.7.8.jar",
          "size": 37351881,
          "sha512": "5a883ed0ac552cabb2555c9b17d4194cad268e6c0069ec4dd51d6473e5da78b5f807dcbb10b42f61c9615e2e70281ed23e82446f9a8065de654c4438e0f03da1",
          "sha256": "0ade0b7d55cb008136d7b58b71100ce017dedb84be20af6da2e76b58b090f699",
          "sha1": "114365a3a1a8748c574e8f281aef008b83c9b733",
          "md5": "2ee48b8def3876bf6d826ee5e4381402"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-desktop-1.7.8.jar",
          "url": "material-icons-extended-desktop-1.7.8.jar",
          "size": 37351881,
          "sha512": "5a883ed0ac552cabb2555c9b17d4194cad268e6c0069ec4dd51d6473e5da78b5f807dcbb10b42f61c9615e2e70281ed23e82446f9a8065de654c4438e0f03da1",
          "sha256": "0ade0b7d55cb008136d7b58b71100ce017dedb84be20af6da2e76b58b090f699",
          "sha1": "114365a3a1a8748c574e8f281aef008b83c9b733",
          "md5": "2ee48b8def3876bf6d826ee5e4381402"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "material-icons-extended-desktop-1.7.8-sources.jar",
          "url": "material-icons-extended-desktop-1.7.8-sources.jar",
          "size": 12086044,
          "sha512": "f24f98c6a99f38ceefae7eca7ba34093810e1e631d210cbdff05b35f906230d7cffcbe863bdaed0972b43b050efc91bcb0db681c8b75f1f275e8c0f94eaf05da",
          "sha256": "77b7e782a519a3e074fc91e09d59334ac1b815edd87d2e89c0c9ca7c95678e93",
          "sha1": "fd5e20a9a49831a8c9ce04b7012d1ea5ff755a7c",
          "md5": "50ad9455a4e80286f2e50f2dc8c6addb"
        }
      ]
    }
  ]
}