{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-annotation/1.12.1/runtime-annotation-1.12.1.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-annotation",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "16239466"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-annotation.aar",
          "url": "runtime-annotation-android-1.12.1.aar",
          "size": 8879,
          "sha512": "4d4269e4e4122296be6ec090a34c2159c4595f98b72daec41a392be68d22a6dd944f1590abe0b903bb5cd997d731b5f338ff733d07e3cedb3a277162e689173a",
          "sha256": "071d6200f5f34ffb5ce69cc19ee8db577c188832bb472779213d4633eca26565",
          "sha1": "b3b290da41f89f33ac97c1880a6c5b44660971f4",
          "md5": "cc37d13496b23c97e69e90ca7b6394be"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-annotation.aar",
          "url": "runtime-annotation-android-1.12.1.aar",
          "size": 8879,
          "sha512": "4d4269e4e4122296be6ec090a34c2159c4595f98b72daec41a392be68d22a6dd944f1590abe0b903bb5cd997d731b5f338ff733d07e3cedb3a277162e689173a",
          "sha256": "071d6200f5f34ffb5ce69cc19ee8db577c188832bb472779213d4633eca26565",
          "sha1": "b3b290da41f89f33ac97c1880a6c5b44660971f4",
          "md5": "cc37d13496b23c97e69e90ca7b6394be"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-annotation-android-1.12.1-sources.jar",
          "url": "runtime-annotation-android-1.12.1-sources.jar",
          "size": 12735,
          "sha512": "af051f40e53b47e460a36639af640bf45881bbc690434ffa2b631de52b51bcc13ba92ead8f881a0a40a1d7d2d9db3645432105b00d3de10a45ee9ea6533b5474",
          "sha256": "faddbe6240e43542fcccfb4106f15b36494facbd81dc18e58124c1327dfe4fb1",
          "sha1": "6a0e4345998bd6d41c0e9993d0bb23c4a96ba112",
          "md5": "df620258a86188e198205b43603ff9f5"
        },
        {
          "name": "runtime-annotation-1.12.1-samples-sources.jar",
          "url": "runtime-annotation-android-1.12.1-samples-sources.jar",
          "size": 6132,
          "sha512": "e91df26f47eae05520743a16fcbfeb1d206772dea180805eb6a8087ff486a331ee732dc964f00b54b49bbad86d85befb51a642a0826dfdad054db9f4bd3095c3",
          "sha256": "728e5ed27524324dc79b771f67891f711058041ef3d6b805edbe0e4c0fea3fd4",
          "sha1": "7f2edc491e066e09b04bcb56725b8eacb21ed045",
          "md5": "87b2c17252a543f8eb8c4573978f8d77"
        }
      ]
    }
  ]
}