{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-inspector",
    "version": "1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-inspector-1.11.1.aar",
          "url": "media3-inspector-1.11.1.aar",
          "size": 39855,
          "sha512": "9c669bafd3f4d0f674808d5e13c936b43f4df2114d5b60036243f140e7c5d0743eaa188b07a1906934d0d2f8195dadab28d28b2aa21957d7ccbb4909bdddf5c2",
          "sha256": "46d42f9a2eaa2ced58cd00e2f4d983817a83a181b45c32d923a74fdf9cb8c89d",
          "sha1": "a98483b2558ee51490cf8613dca329e16de09714",
          "md5": "befc9921d662423903228bab5d12c217"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-inspector-1.11.1.aar",
          "url": "media3-inspector-1.11.1.aar",
          "size": 39855,
          "sha512": "9c669bafd3f4d0f674808d5e13c936b43f4df2114d5b60036243f140e7c5d0743eaa188b07a1906934d0d2f8195dadab28d28b2aa21957d7ccbb4909bdddf5c2",
          "sha256": "46d42f9a2eaa2ced58cd00e2f4d983817a83a181b45c32d923a74fdf9cb8c89d",
          "sha1": "a98483b2558ee51490cf8613dca329e16de09714",
          "md5": "befc9921d662423903228bab5d12c217"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-inspector-1.11.1-sources.jar",
          "url": "media3-inspector-1.11.1-sources.jar",
          "size": 22855,
          "sha512": "b426a88019619dea514d088a809fb3a4abcbb22c75a684d6d5444d5e8c95249f6838ce55d98caa4dcafc2039f0d9a7df9e000fee70ce37ec20ecfcc1bb15b546",
          "sha256": "a9acbe36987dd452cc40540affbce6bdd4e37e995d93ab8d327b049eba06c600",
          "sha1": "f4766d537f459bf8e33a88192ad67d994f253151",
          "md5": "61a2dfe4f13f7d0b81b7ed22359afec4"
        }
      ]
    }
  ]
}
