{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core-okio/1.2.1/datastore-core-okio-1.2.1.module",
    "group": "androidx.datastore",
    "module": "datastore-core-okio",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14975342"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.2.1.jar",
          "url": "datastore-core-okio-jvm-1.2.1.jar",
          "size": 31870,
          "sha512": "6a2e018ac99be0e909c3401b508dd4fbdabf054d178f7ea77147140963682ba27f30a492821a37cb687b70902f45d3ef73f98b6220b205c5d38cf3b5eacd5d03",
          "sha256": "7ade6239a67674834f5724428e772c4176229ed30be253ac7e52082a2907ee05",
          "sha1": "16e01a0603ce8cf206b21a304ff1ded7a9bff1da",
          "md5": "38c87b659b5e43255f87474fab30457f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.2.1.jar",
          "url": "datastore-core-okio-jvm-1.2.1.jar",
          "size": 31870,
          "sha512": "6a2e018ac99be0e909c3401b508dd4fbdabf054d178f7ea77147140963682ba27f30a492821a37cb687b70902f45d3ef73f98b6220b205c5d38cf3b5eacd5d03",
          "sha256": "7ade6239a67674834f5724428e772c4176229ed30be253ac7e52082a2907ee05",
          "sha1": "16e01a0603ce8cf206b21a304ff1ded7a9bff1da",
          "md5": "38c87b659b5e43255f87474fab30457f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.2.1-sources.jar",
          "url": "datastore-core-okio-jvm-1.2.1-sources.jar",
          "size": 11341,
          "sha512": "81c11f5985fce054201e52674c990918ed405760d930033890d5efa64fd414b3cde88b1055405fce8eaa20cb49d64d0b6e0902ecc0a43a6326d2ad62c5b25497",
          "sha256": "0c4f2ea799f747175798b8669e1aab83db7ed2344199bd973a6db640c7cdba46",
          "sha1": "b68093cf47a56fd05f747863848a582aedbd0348",
          "md5": "4eaa526340d4bc798a6d11e309d8a46b"
        }
      ]
    }
  ]
}