{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource",
    "version": "1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.11.1.aar",
          "url": "media3-datasource-1.11.1.aar",
          "size": 168578,
          "sha512": "c27f604ed6cb4d58673aa8c961f4b479bc41c77f6bd439ee3bbb2442a353885926f0e9949af3a8e2bf2865d1864e5841a123b2ed4f3b0d7da6d79ddaa9a6a96f",
          "sha256": "490fd23c7562a6a1183d63bf854b291ae3a77dce5a151450aa1937148c80c60b",
          "sha1": "f45b0955a50d78e448c054fc70588360c069165b",
          "md5": "16c865a875271a66d095e8408ef604a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.11.1.aar",
          "url": "media3-datasource-1.11.1.aar",
          "size": 168578,
          "sha512": "c27f604ed6cb4d58673aa8c961f4b479bc41c77f6bd439ee3bbb2442a353885926f0e9949af3a8e2bf2865d1864e5841a123b2ed4f3b0d7da6d79ddaa9a6a96f",
          "sha256": "490fd23c7562a6a1183d63bf854b291ae3a77dce5a151450aa1937148c80c60b",
          "sha1": "f45b0955a50d78e448c054fc70588360c069165b",
          "md5": "16c865a875271a66d095e8408ef604a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-1.11.1-sources.jar",
          "url": "media3-datasource-1.11.1-sources.jar",
          "size": 139089,
          "sha512": "7133fbea34a2520d2a98a532e8d7f82cdd0a2bda714a2a0504f1a8a787ea31dfece1b35b4d3369392518d5377bb3ea67e4615c499b582b8728ef712e534d1388",
          "sha256": "a54ddd9858ed2de57e07c5461dcebdae7a53d92a60210a2a3f5bf501398a5e4a",
          "sha1": "ee38b0a6b15ee2afb68099b9781a273188158e27",
          "md5": "6d2c78afb5fe3e8e7aee2d868da13c37"
        }
      ]
    }
  ]
}
