{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.19.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "16338100"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.19.1-sources.jar",
          "url": "core-1.19.1-sources.jar",
          "size": 1076958,
          "sha512": "0c88d2a6720df01d6d8b213136d6562ab6b6e3dcd30d3addf5c38f5d6c0c5fdbf5f4bb091cbd29353f2456e15b108bbd34ffeaa7627bb16ffb652eef58131477",
          "sha256": "dabdcce52939de70764cf967c7844da2222830d6a17ae20eefb41b2051964712",
          "sha1": "df0fc1c85262ace786b7aa8d45fb3dc7f127ae24",
          "md5": "3ccc28533344eb2e1f4bc25e64fb39ef"
        },
        {
          "name": "core-1.19.1-samples-sources.jar",
          "url": "core-1.19.1-samples-sources.jar",
          "size": 6272,
          "sha512": "a9246de87cc8f33a38346139c37243099d11256100fe035083f43341e6aefea350781a64679c00436d2539a6c65de2a8e0152eb40f07234005f46d98cef4e723",
          "sha256": "a487797562cc32e1233334574ca1681d36063ec9a4399c44e9d007a633dcd3a3",
          "sha1": "26479f91ea0d83ae369a781b380b9b9a54551741",
          "md5": "93b1b3eea236c8e04cd69e0d2853daf5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.19.1.aar",
          "url": "core-1.19.1.aar",
          "size": 1604983,
          "sha512": "46c046d8b7b51dc18bf5255ff6d644ad5c3e24463af6651f4256aa4bc116908e203051b2cea0e1494ebefd451f84d285e5e5364820e1ea16548c9ef4c16f6031",
          "sha256": "08108ea780205bd54603088a62a6dd5378f63bd25542674be24cd4cdb8191a09",
          "sha1": "9f58cde6b5660496ad3380c38a385b6a12c21a9a",
          "md5": "bdf128d29ca1136de5f231b05eae0f76"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.19.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.19.1.aar",
          "url": "core-1.19.1.aar",
          "size": 1604983,
          "sha512": "46c046d8b7b51dc18bf5255ff6d644ad5c3e24463af6651f4256aa4bc116908e203051b2cea0e1494ebefd451f84d285e5e5364820e1ea16548c9ef4c16f6031",
          "sha256": "08108ea780205bd54603088a62a6dd5378f63bd25542674be24cd4cdb8191a09",
          "sha1": "9f58cde6b5660496ad3380c38a385b6a12c21a9a",
          "md5": "bdf128d29ca1136de5f231b05eae0f76"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.19.1-versionMetadata.json",
          "url": "core-1.19.1-versionMetadata.json",
          "size": 338401,
          "sha512": "55549c54e97cea2a48b9b9fe104a0654f71d95d7d2e9fb52a81d6088c9add4a122260b1fac4d0937dda0152d1ff6055b351de4332cb0cb18271de17268ec26bf",
          "sha256": "e3cf52d0805ad0d02823bf679d1ec966b21004d0386988a0cdfb2706fc763b73",
          "sha1": "14cf51db164e1d8430ecd335f287f9e263007b75",
          "md5": "3271c349a61b43ed146e9af0f75f06bf"
        }
      ]
    }
  ]
}