{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.11.1.aar",
          "url": "media3-ui-1.11.1.aar",
          "size": 337017,
          "sha512": "6fb34212eb6284b38766dd54aafd9fdc87d1d4ca5f09d724b95bdb2fbaeeb75a5deba4399812cb5911ca71ab4f1798fed41a01b18ae03d6451e1c454d0771b29",
          "sha256": "bbd94f6d0e504931235d87275c3c5bf4f0a48e0008d8d12efc79f96fc8a3011f",
          "sha1": "a1ea4d7466f633b31609fd7c38d69c4f8d835f26",
          "md5": "cfebd36094257b97ece31f39e312fe1f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.11.1.aar",
          "url": "media3-ui-1.11.1.aar",
          "size": 337017,
          "sha512": "6fb34212eb6284b38766dd54aafd9fdc87d1d4ca5f09d724b95bdb2fbaeeb75a5deba4399812cb5911ca71ab4f1798fed41a01b18ae03d6451e1c454d0771b29",
          "sha256": "bbd94f6d0e504931235d87275c3c5bf4f0a48e0008d8d12efc79f96fc8a3011f",
          "sha1": "a1ea4d7466f633b31609fd7c38d69c4f8d835f26",
          "md5": "cfebd36094257b97ece31f39e312fe1f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.11.1-sources.jar",
          "url": "media3-ui-1.11.1-sources.jar",
          "size": 120052,
          "sha512": "02b1712ba1d3fe872f3a3a1611ea2a65f84b66f750e72eaef384696156b5b3d6a2016e80e80c246df56d25d8148a89dfd18a030135fae7be0ddb8f6da71dddf6",
          "sha256": "2abea5e2d78f123206a552d99fffd93a54a5c923d78c42416cc5d1d69193c901",
          "sha1": "f6e4bba9c145fdacb0bb8a449681e7cf19d5f457",
          "md5": "615e83887882e958b32a1121db956d91"
        }
      ]
    }
  ]
}
