{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "16239466"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-metadata-1.12.1.jar",
          "url": "ui-graphics-1.12.1.jar",
          "size": 89374,
          "sha512": "c3103360551d4eeb85283dab561e4c036dd67f0865c9e6955ae4fc2ef6054f83d43a06ee1e4af6cf9ed3e719119e9f6dc4d649997c6f6185d13a70cb730c3e74",
          "sha256": "9a72f754ed54ba2c45007d3fbf012743129597c0bcb9292434f82927002380b8",
          "sha1": "55c270240dbbfbbd64c47083a0549492fe9149b1",
          "md5": "e1efcb20d126b6e0f506bc021b09b2ad"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-kotlin-1.12.1-sources.jar",
          "url": "ui-graphics-1.12.1-sources.jar",
          "size": 230043,
          "sha512": "a5680249d558be87278038928ccff51ebaec673db37dd94b8dd05c90676e67404950d67fe531a9f60fed11b03b0d5d54bab42c44810dbda78bb682eecdbd781d",
          "sha256": "1e083b8909d1cfaa604ede481f92e86a0ee9202e69c1f896fe56c8d664893b0b",
          "sha1": "726c46696b55bc0943ef888813265bd5d79238b5",
          "md5": "298232aa520cecb21916ff57f1d98d6d"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.12.1-multiplatform-sources.jar",
          "url": "ui-graphics-1.12.1-multiplatform-sources.jar",
          "size": 283834,
          "sha512": "25c02f90d6b965d1d20c852a623b9b8292db1609218056b9b8370586cfb0b7cb0cd19b94d6f2892c1dd52096c3d9f21ec561feb306abd852fcafb2ac235b9b58",
          "sha256": "1a35a19dd663ea28153ba78cc8b646608575526c3cfd73b1d1f120d35f920c4e",
          "sha1": "a8aaa48b5c2176f694920cfe1055d035afdcd4a9",
          "md5": "00d7c56f37773a91392a1cfd342d9e20"
        },
        {
          "name": "ui-graphics-1.12.1-samples-sources.jar",
          "url": "ui-graphics-1.12.1-samples-sources.jar",
          "size": 14057,
          "sha512": "83a584c940fe937f33150a387a6cf72e049aab5d4336c08a63d55bf6c1ad6c22876e420711af57779f313155338bca2ece68d0ea3026ed4ef7472319eb569a8c",
          "sha256": "b3340db60b9ef81fc81200ff1d26a8bd662ff5375c9b7ee67e3e5bc9629ca8da",
          "sha1": "18396c80df6a7eebdd62b19007562256a6405314",
          "md5": "140eedb1c64b25e724a6b90ed5a3ebac"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-graphics-1.12.1-versionMetadata.json",
          "size": 152269,
          "sha512": "a82ff1af67c24a5d0d7bd1c7f09422fc2d70ad0f325d618b9f1295c90dcc5acbb579216dd02448690cb7fc57877762d1574f13e5be909615faaf0331987feb9d",
          "sha256": "9c5d38f4b982e0407d14e31963447953baf3be8dc35f4c8e163ce367c2a8de22",
          "sha1": "e8a7d5d4635bda8851f3cc507cf0a1c0d899fa5f",
          "md5": "f4a72711da7e0def7c3b39fa00caa174"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-graphics-android/1.12.1/ui-graphics-android-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-android",
        "version": "1.12.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-graphics-android/1.12.1/ui-graphics-android-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-android",
        "version": "1.12.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-graphics-android/1.12.1/ui-graphics-android-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-android",
        "version": "1.12.1"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-jvmstubs/1.12.1/ui-graphics-jvmstubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-jvmstubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-jvmstubs/1.12.1/ui-graphics-jvmstubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-jvmstubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-jvmstubs/1.12.1/ui-graphics-jvmstubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-jvmstubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "androidx.kmp.hasCInterop": false,
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-linuxx64stubs/1.12.1/ui-graphics-linuxx64stubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-linuxx64stubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-linuxx64stubs/1.12.1/ui-graphics-linuxx64stubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-graphics-linuxx64stubs",
        "version": "1.12.1"
      }
    }
  ]
}