{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-preferences-core/1.2.1/datastore-preferences-core-1.2.1.module",
    "group": "androidx.datastore",
    "module": "datastore-preferences-core",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14975342"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core.aar",
          "url": "datastore-preferences-core-android-1.2.1.aar",
          "size": 37489,
          "sha512": "beb80924b7d6f44f3ddff79e6e03a00cb92ed3d5b9ead80b7f655ab26489dd9e4c00345ae7cdf71e0d54604c4d4169e2f0babd18a642e2bea74a4c9bd5b0ea7b",
          "sha256": "48c2235e576fb015f861726e79ee9474948e37da31d2c887c16ebeb46817059f",
          "sha1": "1c6a56a2802d44f6d451101eed3420488a75ca85",
          "md5": "0985deab8dd0328227cde6471a3fb140"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core.aar",
          "url": "datastore-preferences-core-android-1.2.1.aar",
          "size": 37489,
          "sha512": "beb80924b7d6f44f3ddff79e6e03a00cb92ed3d5b9ead80b7f655ab26489dd9e4c00345ae7cdf71e0d54604c4d4169e2f0babd18a642e2bea74a4c9bd5b0ea7b",
          "sha256": "48c2235e576fb015f861726e79ee9474948e37da31d2c887c16ebeb46817059f",
          "sha1": "1c6a56a2802d44f6d451101eed3420488a75ca85",
          "md5": "0985deab8dd0328227cde6471a3fb140"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-android-1.2.1-sources.jar",
          "url": "datastore-preferences-core-android-1.2.1-sources.jar",
          "size": 21658,
          "sha512": "8e0d356c4fc906410258eae158e14e906167a1d0517fcdd50d23857b746e99aea87d1c2da16ab8390d62b8ea272ba3092f7a00e35ee3da20542a8ac1198ce6c8",
          "sha256": "1110e6c688b5f9a59158117b0d934933112cf318e41d2c21b26c1572062a9b7d",
          "sha1": "9b357943b2dad558c1f582e5c3309b4f4bd0fee0",
          "md5": "b00819c76640e951243509ce2e6a144c"
        }
      ]
    }
  ]
}