{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "15569625"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.11.0-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.11.0-sources.jar",
          "size": 4456,
          "sha512": "3210804612a245fa73b486c4128db7505f2a69c52c220f82a4f2757c18f9a103a5869c101b5a0646ac63ea1759bf9a5b73fca7043937d59db689e48627129e67",
          "sha256": "f15c9fbd9ade832f04d2deed9cdc1732697e63b8c34ffae0ada712197abcc6ec",
          "sha1": "6b61248b684d6cc83a4855ef1b98dd76536d8ec7",
          "md5": "c11d236a7f7df430fcfd0e95cbd2e66f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.11.0.aar",
          "url": "lifecycle-viewmodel-ktx-2.11.0.aar",
          "size": 5641,
          "sha512": "4c47ae4cdaf99bd711e4fc1cae4dcd9342b02dd5a70366b49e748433b5f109fa890193f0f352c7b96b151e82483d0a531450e2ec18c04674ce72f721fac1ca77",
          "sha256": "230af6c866076d320d92c22c7c44bb52afca97f6892ddf987e2906ef2919998f",
          "sha1": "1a0332270b7e29c37a1b3c5712248f9f451df667",
          "md5": "669193679510411e4b665120b6ab89c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.11.0.aar",
          "url": "lifecycle-viewmodel-ktx-2.11.0.aar",
          "size": 5641,
          "sha512": "4c47ae4cdaf99bd711e4fc1cae4dcd9342b02dd5a70366b49e748433b5f109fa890193f0f352c7b96b151e82483d0a531450e2ec18c04674ce72f721fac1ca77",
          "sha256": "230af6c866076d320d92c22c7c44bb52afca97f6892ddf987e2906ef2919998f",
          "sha1": "1a0332270b7e29c37a1b3c5712248f9f451df667",
          "md5": "669193679510411e4b665120b6ab89c5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.11.0"
          },
          "reason": "lifecycle-viewmodel-ktx is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.11.0-versionMetadata.json",
          "url": "lifecycle-viewmodel-ktx-2.11.0-versionMetadata.json",
          "size": 1064,
          "sha512": "039a18d778b0ffee554b3fd07f32f3a868e64657b390063295a157f4ac4857853989aa4bcf72c3b49cdc21b1ec163dafc4bc2cc70f8c7c6986eb2130bbbebda0",
          "sha256": "0b7504ca8554d1df14e92a8f7993eae30cf7343537d3bdbb55d5910d69dc9de3",
          "sha1": "5b77039c7e201889161f5edc00b99631d318b120",
          "md5": "fdc4c2ceb77ccd95893781f948ba6670"
        }
      ]
    }
  ]
}