{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0",
      "buildId:": "16343433"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-metadata-2.10.2.jar",
          "url": "navigation-runtime-2.10.2.jar",
          "size": 28171,
          "sha512": "e9f1575afa17de8b1c28236edf54ad771bc03b90464c8ec6703d0320678397ca9c334d454b84a449dfc9167facd7abfd8d7507e543d402fc919a1b75544d2d51",
          "sha256": "c66b5a329fa84075073cdb125fb3d4b81bfae862695e7bb75b99157ea019633d",
          "sha1": "54958516e2745c7bb7180b48b69f939c8adffec7",
          "md5": "6a66ecf181de393cc6045ed37a82cafb"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-kotlin-2.10.2-sources.jar",
          "url": "navigation-runtime-2.10.2-sources.jar",
          "size": 49282,
          "sha512": "7a335da0431705c3fe9e5c1cffa30bf2b07db2298749cb8eacf18b64d86a64c53fbc7ab8301c84e735681b6485f86ca8455b4ec2b4f6bdc10c8fbb8f2f379722",
          "sha256": "449d7284baf18dd54dd92ae05985d6fc600a86a6a637c106b46f616a69d4cd81",
          "sha1": "282e0a54df2d36025718d751703b26f89fc77849",
          "md5": "8b61ea161be154227d7a552d97cc19a6"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.10.2-multiplatform-sources.jar",
          "url": "navigation-runtime-2.10.2-multiplatform-sources.jar",
          "size": 91016,
          "sha512": "7c6c9ff97a134efba169772647b756e4886a55a5b51931dcae1067c511fa56b5c14f636d1b1a0d21bfe98d3b81f2836c3f4b4817ee6b84a4eb917b196a4ffa77",
          "sha256": "6ac7ecdd49b0e1dda3324e63e6bb43c2849ca014718463f31c3d702912f5989b",
          "sha1": "9735c83239b17573155550b419e4b5de4fde1419",
          "md5": "c1c8b3e622857725a38628ef21bf1800"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.10.2"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "navigation-runtime-2.10.2-versionMetadata.json",
          "size": 19368,
          "sha512": "863665648011a543ad71309e477884c7833d6e6b40ee30e168e2a1b2616b26e2cdaee12001d9243cba1b615670184478a750325ec5b2d4434b8595d517174ee6",
          "sha256": "b79f494fdb0f2868c3a4e3df8cedd6cdf22f94a8b794417db7b117d8e5cbbb9a",
          "sha1": "46828235a5d951de3c942e36041655f09a9481ce",
          "md5": "0e3992b8969bc50b8a1fb143d352a99f"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation-runtime-android/2.10.2/navigation-runtime-android-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-android",
        "version": "2.10.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation-runtime-android/2.10.2/navigation-runtime-android-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-android",
        "version": "2.10.2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation-runtime-android/2.10.2/navigation-runtime-android-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-android",
        "version": "2.10.2"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation-runtime-desktop/2.10.2/navigation-runtime-desktop-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-desktop",
        "version": "2.10.2"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation-runtime-desktop/2.10.2/navigation-runtime-desktop-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-desktop",
        "version": "2.10.2"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation-runtime-desktop/2.10.2/navigation-runtime-desktop-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-desktop",
        "version": "2.10.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-iosarm64/2.10.2/navigation-runtime-iosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-iosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-iosarm64/2.10.2/navigation-runtime-iosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-iosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-iosarm64/2.10.2/navigation-runtime-iosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-iosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-iossimulatorarm64/2.10.2/navigation-runtime-iossimulatorarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-iossimulatorarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-iossimulatorarm64/2.10.2/navigation-runtime-iossimulatorarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-iossimulatorarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-iossimulatorarm64/2.10.2/navigation-runtime-iossimulatorarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-iossimulatorarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../navigation-runtime-js/2.10.2/navigation-runtime-js-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-js",
        "version": "2.10.2"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../navigation-runtime-js/2.10.2/navigation-runtime-js-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-js",
        "version": "2.10.2"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../navigation-runtime-js/2.10.2/navigation-runtime-js-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-js",
        "version": "2.10.2"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-linuxarm64/2.10.2/navigation-runtime-linuxarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-linuxarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-linuxarm64/2.10.2/navigation-runtime-linuxarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-linuxarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-linuxx64/2.10.2/navigation-runtime-linuxx64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-linuxx64",
        "version": "2.10.2"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-linuxx64/2.10.2/navigation-runtime-linuxx64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-linuxx64",
        "version": "2.10.2"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-macosarm64/2.10.2/navigation-runtime-macosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-macosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-macosarm64/2.10.2/navigation-runtime-macosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-macosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-macosarm64/2.10.2/navigation-runtime-macosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-macosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-tvosarm64/2.10.2/navigation-runtime-tvosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-tvosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-tvosarm64/2.10.2/navigation-runtime-tvosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-tvosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-tvosarm64/2.10.2/navigation-runtime-tvosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-tvosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-tvossimulatorarm64/2.10.2/navigation-runtime-tvossimulatorarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-tvossimulatorarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-tvossimulatorarm64/2.10.2/navigation-runtime-tvossimulatorarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-tvossimulatorarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-tvossimulatorarm64/2.10.2/navigation-runtime-tvossimulatorarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-tvossimulatorarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../navigation-runtime-wasm-js/2.10.2/navigation-runtime-wasm-js-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-wasm-js",
        "version": "2.10.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../navigation-runtime-wasm-js/2.10.2/navigation-runtime-wasm-js-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-wasm-js",
        "version": "2.10.2"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../navigation-runtime-wasm-js/2.10.2/navigation-runtime-wasm-js-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-wasm-js",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchosarm32/2.10.2/navigation-runtime-watchosarm32-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchosarm32",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchosarm32/2.10.2/navigation-runtime-watchosarm32-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchosarm32",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchosarm32/2.10.2/navigation-runtime-watchosarm32-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchosarm32",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchosarm64/2.10.2/navigation-runtime-watchosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchosarm64/2.10.2/navigation-runtime-watchosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchosarm64/2.10.2/navigation-runtime-watchosarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchosarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchosdevicearm64/2.10.2/navigation-runtime-watchosdevicearm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchosdevicearm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchosdevicearm64/2.10.2/navigation-runtime-watchosdevicearm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchosdevicearm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchosdevicearm64/2.10.2/navigation-runtime-watchosdevicearm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchosdevicearm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchossimulatorarm64/2.10.2/navigation-runtime-watchossimulatorarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchossimulatorarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchossimulatorarm64/2.10.2/navigation-runtime-watchossimulatorarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchossimulatorarm64",
        "version": "2.10.2"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-runtime-watchossimulatorarm64/2.10.2/navigation-runtime-watchossimulatorarm64-2.10.2.module",
        "group": "androidx.navigation",
        "module": "navigation-runtime-watchossimulatorarm64",
        "version": "2.10.2"
      }
    }
  ]
}