{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent/1.1.2/navigationevent-1.1.2.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0-rc-1",
      "buildId:": "15599658"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent.aar",
          "url": "navigationevent-android-1.1.2.aar",
          "size": 49044,
          "sha512": "25efae595b42bfe96c5aae6e5199e86e146a05b5d4c3a51ff2d0faf658ee69c48cf20744f4289d6de0bdfbc0a92bd0cdedb9f4b6775dad93b14bee0aa6f3f260",
          "sha256": "40a357103ab703762bf434f424a8486be18652b4aa25110f0d635a4cef5dcd63",
          "sha1": "03fdcf2b396b8ec003f51b7c274ee0ce7f4f50d0",
          "md5": "a42b3aa9fa83d87e221e4d4fac5009c7"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent.aar",
          "url": "navigationevent-android-1.1.2.aar",
          "size": 49044,
          "sha512": "25efae595b42bfe96c5aae6e5199e86e146a05b5d4c3a51ff2d0faf658ee69c48cf20744f4289d6de0bdfbc0a92bd0cdedb9f4b6775dad93b14bee0aa6f3f260",
          "sha256": "40a357103ab703762bf434f424a8486be18652b4aa25110f0d635a4cef5dcd63",
          "sha1": "03fdcf2b396b8ec003f51b7c274ee0ce7f4f50d0",
          "md5": "a42b3aa9fa83d87e221e4d4fac5009c7"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-android-1.1.2-sources.jar",
          "url": "navigationevent-android-1.1.2-sources.jar",
          "size": 41902,
          "sha512": "9e617fb53c61915e65aeaed6edae0d3cad6c3182b18f8bf736c89b046bd7c5100803b4112c5016557ecb3cd8707eb6300bdffa965665000913a0af26171bcbdf",
          "sha256": "f089d4ea9953c8db3b00829a751c4997300685cb597d604444952ff3ff130ffe",
          "sha1": "d4cf27ad83468b2feda5d9703f7c6fc1af023665",
          "md5": "dae615431373f8a1a115b7cf510c8b31"
        },
        {
          "name": "navigationevent-1.1.2-samples-sources.jar",
          "url": "navigationevent-android-1.1.2-samples-sources.jar",
          "size": 5859,
          "sha512": "ade557bee51aab3e41cde6381162fb98e8053ab0a9349fad48367d34bd5cebab5a76cb5081ad0f933e4a3f27ffb56f4ada3f1c5b2563acde1cad98d44d2fc1ac",
          "sha256": "df63ae9684f469f4538795438481b802b394d365566b5af25487e0eef2f4ac6f",
          "sha1": "b7d83bf2bf811c87eec0c4133cf342e08043060e",
          "md5": "3dc3a37e0a809197bcd92e7bf8e9c888"
        }
      ]
    }
  ]
}