{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "16239466"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-metadata-1.12.1.jar",
          "url": "ui-test-1.12.1.jar",
          "size": 61732,
          "sha512": "1f7ac985c51b104bf351793d961acbb61c4619fcd3dad0d43d82e9966d971a482b31f6c9f5c9f927638427be1e4772c005dc3da11a38fabfac6678a5334702e4",
          "sha256": "48dbf78c3fa9a98be9ae52eff1d1083e4526a1713071deb8e8dc8d67be60e0e9",
          "sha1": "8306880018f3d2af46e5e8b4f0dc431c5143622d",
          "md5": "714445e3be081fc5c4d6342b58a10d5d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-kotlin-1.12.1-sources.jar",
          "url": "ui-test-1.12.1-sources.jar",
          "size": 167043,
          "sha512": "21ed6b4b2618cc3670390b43c67283ac311560b093b8b3aefeefd2109880f1d2efc7a620a4edf48d3f19273455bcc7d46a69b48d0ae7359c69e0306d975c0397",
          "sha256": "5c876cb7f53391d6b026874193f16701bdf204a7a611b7cdc8c787206399feaa",
          "sha1": "dfe352372bba2c839c2a6921bc2cb599832a1ba9",
          "md5": "66d5d5658e7c9a55b6821c1514942b5a"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-1.12.1-multiplatform-sources.jar",
          "url": "ui-test-1.12.1-multiplatform-sources.jar",
          "size": 220687,
          "sha512": "264bf4f1fa940f2c2da0fb9c08770a141497d4510b47de37fe0dc16a0494102c6a6341b70c7b3dc7a69337ffd759da7dfe94251e18b6199bd3117b1e1b874eb9",
          "sha256": "8f313957957187a5aa54a81c4c2573b754c406a77417bd861dce2713038bf0d6",
          "sha1": "ac9f758984a34a6eab5ff0994db7bbe17c0d56ba",
          "md5": "dae535470395f7a1adba6c07d8fb4e2a"
        },
        {
          "name": "ui-test-1.12.1-samples-sources.jar",
          "url": "ui-test-1.12.1-samples-sources.jar",
          "size": 23824,
          "sha512": "9e12d5ad1f2ec6ea9ff1dedaef1ac028fd52343e161c6865f4a776ef1690a9b627468b91e2989b5cdc8c0129f1166e722e7ca126bd183e58d412a6c4562db375",
          "sha256": "dd53df2356a0c98fcf1796c602f6220eef60e3932a0e76b5fcddafef7630deb9",
          "sha1": "2a1b93fc0af34d9cfe93d3f47e37249bc996c561",
          "md5": "f071b8a3e62fc15ec1de9da3f2497260"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-test-1.12.1-versionMetadata.json",
          "size": 113095,
          "sha512": "70cfffe2493b48e541f732eebe7972ca44125d01eab6f2449051ab309bc4350bfa36bcf74a55135ac8b64dc4c537744b7c1c9a50ab823467406ac2f3a0ae28bf",
          "sha256": "6b9c71af77829fe6f6b905d1e2c381cb49db7430d5d95fdd627c220820060c17",
          "sha1": "26212f912e9cfed6a5c08effdae5bebb305875bc",
          "md5": "d160cc0d0eab28a9de292730c8d69eb3"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-test-android/1.12.1/ui-test-android-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-android",
        "version": "1.12.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-test-android/1.12.1/ui-test-android-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-android",
        "version": "1.12.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-test-android/1.12.1/ui-test-android-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-android",
        "version": "1.12.1"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-test-jvmstubs/1.12.1/ui-test-jvmstubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-jvmstubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-test-jvmstubs/1.12.1/ui-test-jvmstubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-jvmstubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-test-jvmstubs/1.12.1/ui-test-jvmstubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-jvmstubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "androidx.kmp.hasCInterop": false,
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-test-linuxx64stubs/1.12.1/ui-test-linuxx64stubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-linuxx64stubs",
        "version": "1.12.1"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-test-linuxx64stubs/1.12.1/ui-test-linuxx64stubs-1.12.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-linuxx64stubs",
        "version": "1.12.1"
      }
    }
  ]
}