{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/1.12.1/runtime-1.12.1.module",
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "16239466"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-1.12.1.aar",
          "size": 1997053,
          "sha512": "559ae69823ad55e8bfa9f955743d3d1dc0d8578da732a52ed85cd8490f3c7779041a28c25dbfe94ece4c973d79230fc721d143e491a50596fd01b5c3703295fc",
          "sha256": "1701a61d06d2f6144f2cd8b015abbc5ad6952eacb70c24c208cdfd2bb188dde7",
          "sha1": "ba1fb5d45b4fe4d6a64bade2ed260438e38eba95",
          "md5": "74e37cee1384bdf725eae1d42bcfb734"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "prevents symbols duplication"
        }
      ],
      "files": [
        {
          "name": "runtime.aar",
          "url": "runtime-android-1.12.1.aar",
          "size": 1997053,
          "sha512": "559ae69823ad55e8bfa9f955743d3d1dc0d8578da732a52ed85cd8490f3c7779041a28c25dbfe94ece4c973d79230fc721d143e491a50596fd01b5c3703295fc",
          "sha256": "1701a61d06d2f6144f2cd8b015abbc5ad6952eacb70c24c208cdfd2bb188dde7",
          "sha1": "ba1fb5d45b4fe4d6a64bade2ed260438e38eba95",
          "md5": "74e37cee1384bdf725eae1d42bcfb734"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-android-1.12.1-sources.jar",
          "url": "runtime-android-1.12.1-sources.jar",
          "size": 582544,
          "sha512": "1e6bd375e5f0a9c8ef79b981a60040107876f3577767ad31ef17f7330734efeb9d0ea533c3c744d3d63c9e611333210804db4f8f29e82edee03597f4af32207e",
          "sha256": "645edc8a6d5054f3de00cb097d3fc1f6d0d8e5a75a0f21cec04cbeb77c57d989",
          "sha1": "9071f2608c1db8be1cfbb5a22b4481ef1ed1537b",
          "md5": "b3d05bf52feff518ac8e1e938738d214"
        },
        {
          "name": "runtime-1.12.1-samples-sources.jar",
          "url": "runtime-android-1.12.1-samples-sources.jar",
          "size": 22486,
          "sha512": "2c8fa8c2de234c9eb5d133598e98402e00aa5d85ebbd09b5d92f724dec85aa92b456a1979ee8140e952c5f03a714ea30065798eb7b25317c6b5f4183bdf9ffdc",
          "sha256": "e18ea05c4bebbdca433f3578e9e88501222a110883cbc5d5cbb5c7b0e084d7c7",
          "sha1": "2fdbb37d92349cf956f20e0c1853bf1f632a7537",
          "md5": "386214f618b4065cd2c13c4b9352700a"
        }
      ]
    }
  ]
}