{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.12.1/runtime-saveable-1.12.1.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "16239466"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable.aar",
          "url": "runtime-saveable-android-1.12.1.aar",
          "size": 103620,
          "sha512": "1d2085e69167c5a4a6115323818a5fc0bc8f06f791f2ccce06dd0b74450d5395670daf51e76ba4b2434aba97fce5906f93966e1bd6ddbc0ad0074e961a38e844",
          "sha256": "0c83d47820fbc8ffb6e3e49311ccd4755676d6f94bb8c6d8564ab4c799df8779",
          "sha1": "7a5ddf612079125bf07e31743a17aaf6ff9cd5c4",
          "md5": "5592fee522f98e1bfe2c7d46625aecb8"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "prevents symbols duplication"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable.aar",
          "url": "runtime-saveable-android-1.12.1.aar",
          "size": 103620,
          "sha512": "1d2085e69167c5a4a6115323818a5fc0bc8f06f791f2ccce06dd0b74450d5395670daf51e76ba4b2434aba97fce5906f93966e1bd6ddbc0ad0074e961a38e844",
          "sha256": "0c83d47820fbc8ffb6e3e49311ccd4755676d6f94bb8c6d8564ab4c799df8779",
          "sha1": "7a5ddf612079125bf07e31743a17aaf6ff9cd5c4",
          "md5": "5592fee522f98e1bfe2c7d46625aecb8"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.12.1"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-android-1.12.1-sources.jar",
          "url": "runtime-saveable-android-1.12.1-sources.jar",
          "size": 22187,
          "sha512": "9713e1b173900e92dce745057640ad45bef8492accf83d4b9eb3e185fbdfd60eda75d7d4fca3ee2799c8f5e1b77648f47edf2656779f0adb1d0ffd411dc17373",
          "sha256": "305dfb9a5cdad3c53ba6297db6f96ca9c0d9f1856f83874ee12cc7fb7d028699",
          "sha1": "1e585f2dd9a5146c22550b34220c860b28f11fdd",
          "md5": "e755c638d1e7a0e723295e94507d1929"
        },
        {
          "name": "runtime-saveable-1.12.1-samples-sources.jar",
          "url": "runtime-saveable-android-1.12.1-samples-sources.jar",
          "size": 8887,
          "sha512": "a8cde00e96568aef261135e71a6ad972e30e7eed33418fd6df54568b76dbddffbd6256c9b1fac83d07dc841d7baa406cac3c9ff2d3c35ed8404a82959a708b84",
          "sha256": "d0bd72443e52be73b831a94052e2a1fa733d6dfbbfa9ff57c67075b75c02de0d",
          "sha1": "025057154a62bdfc38f76f025922eb60c146d5f8",
          "md5": "c063e5f9fcccdccfdf59bc1b653b25db"
        }
      ]
    }
  ]
}