{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-core",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14975342"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-metadata-1.2.1.jar",
          "url": "datastore-preferences-core-1.2.1.jar",
          "size": 16370,
          "sha512": "56eb37890141a905866da5e2456b9fa1e69b79ddb29575c9c760d28df8be50c0e870174301875e1e98cdd002afa54e34ba8841b70d136b69ef1e0cda7ba48ff0",
          "sha256": "fe626c202b9ea3b6eace8daaeb0e692fa5d82f5571d2c0375a8dd14f9d3cca66",
          "sha1": "1eac0514db7a2f0cbb5e5b1c386200e599c20b2b",
          "md5": "a302363e95902250f0de462eadd48a02"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-kotlin-1.2.1-sources.jar",
          "url": "datastore-preferences-core-1.2.1-sources.jar",
          "size": 19978,
          "sha512": "fd2d6ff24363a6923af614745b4d5853295f336d97b0636b9d1cf4cd1214f223c9f81b8ca3fdec481a3e20c924aa9fdd39fd1825e4031a6bf8c96ab79328a9d6",
          "sha256": "e166e9be6c0eac5c82c59e97fbd2828384206ac47ebae3ca27cfa0e11a094405",
          "sha1": "dfcd5e91ca958e863ac7eeb52d9f4ca533ef763f",
          "md5": "1ab73f46270db2cc2341399d99035da9"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-1.2.1-multiplatform-sources.jar",
          "url": "datastore-preferences-core-1.2.1-multiplatform-sources.jar",
          "size": 31631,
          "sha512": "626cec524a289dee74b2ea1dd28de2a8ff4f74d95420ccb413c3a27576cb2c0d3b413a204435979598c75550744fd7a0eaeea9f3b24c25b17b5b8a55df5ba0f4",
          "sha256": "c8561886e36f0f1ad3fe410fb5adb2d9e71582a431159145935bc8f515eb2547",
          "sha1": "e8f04249a87c970f3ea95594431ff12790baf12e",
          "md5": "6e726aa6c663da651e98a4020b141457"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "datastore-preferences-core-1.2.1-versionMetadata.json",
          "size": 8682,
          "sha512": "b7b322d64753d8e52b45f7ef66659bc40d47b88eb9aecc9282d4758c44ea2e5ec53768b19aeaa17042d0698bf1326dcf989da68f31467a8e241aaed719c90159",
          "sha256": "19bdad991666ef4cc96e3f090716eaff23394985fde947cb52ed17ed61a99637",
          "sha1": "3aaf10b00f3b708eeb400cf9a1a5371fde8b15bf",
          "md5": "5a6c9d2a91f0e24cd5c67d3815f528f1"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-android/1.2.1/datastore-preferences-core-android-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-android",
        "version": "1.2.1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-android/1.2.1/datastore-preferences-core-android-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-android",
        "version": "1.2.1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-android/1.2.1/datastore-preferences-core-android-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-android",
        "version": "1.2.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.2.1/datastore-preferences-core-iosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.2.1/datastore-preferences-core-iosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosarm64/1.2.1/datastore-preferences-core-iosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.2.1/datastore-preferences-core-iossimulatorarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.2.1/datastore-preferences-core-iossimulatorarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iossimulatorarm64/1.2.1/datastore-preferences-core-iossimulatorarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iossimulatorarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.2.1/datastore-preferences-core-iosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.2.1/datastore-preferences-core-iosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-iosx64/1.2.1/datastore-preferences-core-iosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-iosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.2.1/datastore-preferences-core-jvm-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.2.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.2.1/datastore-preferences-core-jvm-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.2.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-jvm/1.2.1/datastore-preferences-core-jvm-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-jvm",
        "version": "1.2.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-linuxarm64/1.2.1/datastore-preferences-core-linuxarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-linuxarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-linuxarm64/1.2.1/datastore-preferences-core-linuxarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-linuxarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-linuxx64/1.2.1/datastore-preferences-core-linuxx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-linuxx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-linuxx64/1.2.1/datastore-preferences-core-linuxx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-linuxx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.2.1/datastore-preferences-core-macosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.2.1/datastore-preferences-core-macosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosarm64/1.2.1/datastore-preferences-core-macosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.2.1/datastore-preferences-core-macosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.2.1/datastore-preferences-core-macosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-macosx64/1.2.1/datastore-preferences-core-macosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-macosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-tvosarm64/1.2.1/datastore-preferences-core-tvosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-tvosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-tvosarm64/1.2.1/datastore-preferences-core-tvosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-tvosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-tvosarm64/1.2.1/datastore-preferences-core-tvosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-tvosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-tvossimulatorarm64/1.2.1/datastore-preferences-core-tvossimulatorarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-tvossimulatorarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-tvossimulatorarm64/1.2.1/datastore-preferences-core-tvossimulatorarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-tvossimulatorarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-tvossimulatorarm64/1.2.1/datastore-preferences-core-tvossimulatorarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-tvossimulatorarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-tvosx64/1.2.1/datastore-preferences-core-tvosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-tvosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-tvosx64/1.2.1/datastore-preferences-core-tvosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-tvosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-tvosx64/1.2.1/datastore-preferences-core-tvosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-tvosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-wasm-js/1.2.1/datastore-preferences-core-wasm-js-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-wasm-js",
        "version": "1.2.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-wasm-js/1.2.1/datastore-preferences-core-wasm-js-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-wasm-js",
        "version": "1.2.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-wasm-js/1.2.1/datastore-preferences-core-wasm-js-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-wasm-js",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosarm32/1.2.1/datastore-preferences-core-watchosarm32-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosarm32",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosarm32/1.2.1/datastore-preferences-core-watchosarm32-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosarm32",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosarm32/1.2.1/datastore-preferences-core-watchosarm32-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosarm32",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosarm64/1.2.1/datastore-preferences-core-watchosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosarm64/1.2.1/datastore-preferences-core-watchosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosarm64/1.2.1/datastore-preferences-core-watchosarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosdevicearm64/1.2.1/datastore-preferences-core-watchosdevicearm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosdevicearm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosdevicearm64/1.2.1/datastore-preferences-core-watchosdevicearm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosdevicearm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosdevicearm64/1.2.1/datastore-preferences-core-watchosdevicearm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosdevicearm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchossimulatorarm64/1.2.1/datastore-preferences-core-watchossimulatorarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchossimulatorarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchossimulatorarm64/1.2.1/datastore-preferences-core-watchossimulatorarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchossimulatorarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchossimulatorarm64/1.2.1/datastore-preferences-core-watchossimulatorarm64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchossimulatorarm64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosx64/1.2.1/datastore-preferences-core-watchosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosx64/1.2.1/datastore-preferences-core-watchosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosx64",
        "version": "1.2.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../datastore-preferences-core-watchosx64/1.2.1/datastore-preferences-core-watchosx64-1.2.1.module",
        "group": "androidx.datastore",
        "module": "datastore-preferences-core-watchosx64",
        "version": "1.2.1"
      }
    }
  ]
}