{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.12.1/material-ripple-1.12.1.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0",
      "buildId:": "16239466"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple.aar",
          "url": "material-ripple-android-1.12.1.aar",
          "size": 93950,
          "sha512": "28f4e7b8f451e8f77993663c0717782586fb00a9f2c21ef835803e2a2389d2228838eb8ab24ff99f99cae187f0dcfd2db28caa261848f0ba4d4cccc2f9b809f9",
          "sha256": "795d8742165875ee96383ca64ff4cd8bc12b83efb0918f68472e7c2f9d5826df",
          "sha1": "e37be16b3e6af5ffe5570f3222b1068e456c40ff",
          "md5": "f999a12d8be49b6f970b9c9f3acd1c85"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple.aar",
          "url": "material-ripple-android-1.12.1.aar",
          "size": 93950,
          "sha512": "28f4e7b8f451e8f77993663c0717782586fb00a9f2c21ef835803e2a2389d2228838eb8ab24ff99f99cae187f0dcfd2db28caa261848f0ba4d4cccc2f9b809f9",
          "sha256": "795d8742165875ee96383ca64ff4cd8bc12b83efb0918f68472e7c2f9d5826df",
          "sha1": "e37be16b3e6af5ffe5570f3222b1068e456c40ff",
          "md5": "f999a12d8be49b6f970b9c9f3acd1c85"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "material-ripple-android-1.12.1-sources.jar",
          "url": "material-ripple-android-1.12.1-sources.jar",
          "size": 30434,
          "sha512": "b81649dabaddc86179a78b04a73d317eaf1b01654b65ecf6ac38a975bd90b44d81c68ab136c8dc563a816895470bcaf196521d9a96b60906f6c486c3e449fc91",
          "sha256": "65b50cad7a19b27d55e319536478069bef9e7b185c55a5363f8660fcef7bab93",
          "sha1": "027abc09af255dd5766b93fcba0cf7c19f7cee8e",
          "md5": "31b23cdc7819815b3f9bf8b847449482"
        }
      ]
    }
  ]
}